accountbook/urls.py
from django.urls import path

from accountbook import views

app_name = 'accountbook'

urlpatterns = [
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('list/', views.AccountBookListView.as_view(), name='accountbook_list'),
    path('create/', views.AccountBookCreateView.as_view(), name='accountbook_create'),
    path('update/<int:pk>/', views.AccountBookUpdateView.as_view(), name='accountbook_update'),
    path('delete/<int:pk>/', views.AccountBookDeleteView.as_view(), name='accountbook_delete'),
    path('',views.dashboard_accountbook, name = 'accountbook_dashboard'),
]

chart_test/urls.py
from django.urls import path

from chart_test import views

app_name = 'chart_test'

urlpatterns = [
    path('', views.show_chart, name='show_chart')
]

householdAccountBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chart_test/', include('chart_test.urls')),
    path('accountbook/', include('accountbook.urls'))
]

accountbook/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=20)
    bgcolor = models.CharField(max_length=7)
    # accountbook_set: 적당 category와 연결되어있는 accountbook 여러개를 가져온다.

    class Meta:
        verbose_name_plural = "categories"
    def __str__(self):
        return f'{self.name}:{self.bgcolor}'

class AccountBook(models.Model):
    TYPE_CHOICES = [
        (0, '지출'),
        (1, '소비'),
    ]
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, default=0)
    price = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)    # models.CASCADE()에서 () 삭제
    time = models.DateTimeField()
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

def __str__(self):
    return f'{self.get_type_display()} {self.price} {self.contents} {self.category} {self.time}'

chart_test/models.py
from django.db import models

# Create your models here.

accountbook/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from accountbook.models import Category, AccountBook


# Create your views here.
class CategoryListView(ListView):
    model = Category #Category 테이블 모든 Category 가져와서 -> category_list 라는 context에 담아 category_list.html에 넘긴다


class AccountBookListView(ListView):
    model = AccountBook


class AccountBookCreateView(CreateView):
    model = AccountBook
    fields = '__all__'
    template_name_suffix = '_create'
    success_url = reverse_lazy('accountbook:accountbook_list')

class AccountBookUpdateView(UpdateView):
    model = AccountBook
    fields = '__all__'
    template_name_suffix = '_update'
    success_url = reverse_lazy('accountbook:accountbook_list')

class AccountBookDeleteView(DeleteView):
    model = AccountBook
    success_url = reverse_lazy('accountbook:accountbook_list')

def dashboard_accountbook(request):
    accountbook_list = AccountBook.objects.all() #all(): 전체, filter(): 필터링, get(): 하나 가져옴, none(): 안가져온
    context = {
        'accountbook_list': accountbook_list,
    }
    return render(request, 'accountbook/accountbook_dashboard.html', context = context)

chart_test/views.py
import json

from django.shortcuts import render

# Create your views here.

def show_chart(request):
    with open('data/data.json', 'r', encoding='utf-8') as file:
        json_data = json.load(file)

    name = [item['name'] for item in json_data]
    price = [item['price'] for item in json_data]
    ctgColor = [item['ctgColor'] for item in json_data]

    context = {
        'name' : name,
        'price' : price,
        'ctgColor' : ctgColor
    }
    return render(request, 'chart_test/chart_view.html', context=context)

accountbook/templates/accountbook/accountBook_dashboard.html
{% extends 'base.html' %}

{% block title %}가계부{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'accountbook/css/dashboard.css' %}">
{% endblock %}

{% block content %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        let accountbookDates = [];
    </script>
    <div id="nav-main">
        <nav id="nav">
            <h1>가계부</h1>
            <div class="nav-item"><a href="{% url 'accountbook:accountbook_dashboard' %}"
                                     class="nav-link action">대시보드</a>
            </div>
            <div class="nav-item"><a href="{% url 'accountbook:accountbook_create' %}" class="nav-link">지출계획서</a></div>
        </nav>
        <main id="dashboard">
            <div id="weekly">
                <div id="weekly-chart">
                    <h1 class="chart-title"></h1>
                    <canvas id="myChart"></canvas>
                </div>
                <div id="weekly-table">
                    <div class="table">
                    </div>
                </div>
            </div>
            <div id="monthly-daily">
                <div id="monthly">
                    <div class="calendar-title container">
                        <button class="btn prev-date" onclick="changeMonth(-1)">&lt;</button>
                        <h1 class="calendar-current-month">2024년 5월</h1>
                        <button class="btn next-date" onclick="changeMonth(1)">&gt;</button>
                    </div>
                    <table class="calendar" border="1">
                        <thead>
                        <tr>
                            <th>Su</th>
                            <th>Mo</th>
                            <th>Tu</th>
                            <th>We</th>
                            <th>Th</th>
                            <th>Fr</th>
                            <th>Sa</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>

                <div id="daily">
                    {% load humanize %}
                    <h1 class="title-date">ALL</h1>
                    <div class="container">
                        {% for accountbook in accountbook_list %}
                            <div class="row-account-book">
                                <div class="d-flex justify-content-between">
                                    <div class="daily-date">{{ accountbook.time|date:"Y.m.d" }}</div>
                                    <div class="daily-category">
                                    <span class="badge"
                                          style="background-color: {{ accountbook.category.bgcolor }}">{{ accountbook.category.name }}</span>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <div class="daily-contents">
                                        <a href="{% url 'accountbook:accountbook_update' pk=accountbook.id %}">{{ accountbook.contents }}</a>
                                        <a href="{% url 'accountbook:accountbook_delete' pk=accountbook.id %}">⚒️</a>
                                    </div>
                                    <div class="daily-type_price"><span
                                            class="daily-type">{{ accountbook.get_type_display }} </span><span
                                            class="daily-price">{{ accountbook.price|intcomma }}</span>원
                                    </div>
                                </div>
                            </div>
                            <script>accountbookDates.push("{{ accountbook.time|date:'Y.n.j' }}");</script>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

accountbook/templates/accountbook/accountbook_confirm_delete.html
{% extends 'base.html' %}

{% block title %}AccountBook Update{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ accountbook }} 진짜 지울까요?? <br>
        <input type="submit" value="DELETE">
        <input type="button" value="Cancel" onclick="history.back()">

    </form>
{% endblock %}

accountbook/templates/accountbook/accountbook_create.html
{% extends 'base.html' %}

{% block title %}AccountBook Create{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

accountbook/templates/accountbook/accountbook_list.html
{% extends 'base.html' %}

{% block title %}AccountBook List{% endblock %}

{% block content %}
    <h1>AccountBook</h1>
    <ul>
        {% for accountbook in accountbook_list %}
            <li>{{ accountbook }}</li>
        {% endfor %}
    </ul>
{% endblock %}

accountbook/templates/accountbook/accountbook_update.html
{% extends 'base.html' %}

{% block title %}AccountBook Update{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

accountbook/templates/accountbook/category_list.html
{% extends 'base.html' %}

{% block title %}Category List{% endblock %}

{% block content %}
    <h1>Category</h1>
    <ul>
        {% for category in category_list %}
            <li style="background-color: {{ category.bgcolor }}; display: inline;
                    border-radius: 10px; padding: 10px">{{ category.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

chart_test/templates/chart_test/chart_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>C H A R T</title>
</head>
<body>
    {{ name }}
    {{ price }}
    {{ ctgColor }}

<div>
  <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const ctx = document.getElementById('myChart')
    const data = {
        labels: {{ name|safe }},
        price: {{ price|safe }},
        ctgColor: {{ ctgColor|safe }}
    }

    const chartData = {
        labels: data.labels,
        datasets: [{
            data: data.price,
            backgroundColor:data.ctgColor
        }]
    }

    const config = {
        type: 'pie',
        data:chartData,
        options:{
            responsive:false,
            plugins:{
                legend:{
                    display:false,
                },
                title :{
                    display: true,
                    text:'chart test'
                }
            }
        }
    }

    new Chart(ctx, config)
</script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'accountbook/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'accountbook/css/nav.css' %}">
    {% block css %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>